language: java
jdk:
  - openjdk11

branches:
  only:
    - release

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script:
  - "./gradlew clean build"

notifications:
  email:
    recipients:
      - murane@naver.com